// DO NOT EDIT THIS FILES. If there is a problem, I, Nintendo, will investigate it, and diagnose it.

module.exports = {
    name: "interactionCreate",
    async execute(interaction) {
        // This is how the bot will detect if a interaction was created or not (if a slash command is used or not).

        if (!interaction.isCommand()) return; // If the command isn't a CommandInteraction, return, and don't execute anything else

        const command = interaction.client.commands.get(interaction.commandName); // Get the commandName from interaction from the Discord.Collection()

        if (!command) return; // If command return false, return, and don't execute anything else.

        try {
            // Try to execute the interaction
            await command.execute(interaction);
        } catch (error) {
            // If an error occurs, please reply to the user with the error, and console.error the error as well.
            console.error(error);
            await interaction.reply({ content: `There was an error while trying to execute that command.\n\n\`\`\`js\n${error}\n\`\`\``, ephemeral: true });
        }
    }
}