// DO NOT EDIT THIS FILES. If there is a problem, I, Nintendo, will investigate it, and diagnose it.

module.exports = {
    name: "ready",
    once: true,
    execute(client) {
        // Once the client is ready, execute this code ONLY ONCE.
        console.log(`Ready! Logged in as ${client.user.tag}.`);
    }
}